name: lint-backend

on:
  push:
    paths:
      - backend/**"
  pull_request:
    paths:
      - backend/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: run ruff check
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"

  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: run ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
          version: "latest"
